### ISSUE TITLE
international

### ISSUE THREAD

**Issue by atteism** [bitmazk/django-booking#1]
in models:

from international.models import countries

...where is international coming from? (I installed using pip, got 0.7)

**Comment by dkaufhold** [comment]
For now you can install the latest commit from this repo https://bitbucket.org/dkaufhold/django-international.

This link is missing in the `setup.py` dependencies. I'll update it soon.

**Comment by atteism** [comment]
Thank you! Also, django.conf.urls.default (urls.py) was removed in Django 1.6. https://docs.djangoproject.com/en/1.6/internals/deprecation/#id1

**Comment by dkaufhold** [comment]
Compatibility for `django.conf.urls.defaults` and dependencies (https://bitbucket.org/dkaufhold/django-international) are fixed in the latest release (v0.7.1)
