### ISSUE TITLE
Problem with migration

### ISSUE THREAD

**Issue by jadjay** [bitmazk/django-booking#10]
$ ./manage.py migrate booking                                                       
Operations to perform:
  Apply all migrations: booking
Running migrations:
  Applying booking.0002_auto_20170308_2327...Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
...
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: booking_bookingstatus_translation

**Comment by Tyrdall** [comment]
@jadjay Which setup to you have? All apps up to date?

**Comment by jadjay** [comment]
Yes... I mean ...
"pip update/upgrade all" ok
I'm using python2.7...

**Comment by Tyrdall** [comment]
@jadjay Seems like you skipped/faked the initial migration. Did you run something like "./manage.py migrate --fake-initial" before? Anyway, you need to re-run all migrations from this app. That's an issue of your local setup only.

**Comment by jadjay** [comment]
> Did you run something like "./manage.py migrate --fake-initial" before? 

No, should I had to ?
This isn't told in your Readme.

**Comment by Tyrdall** [comment]
No, it's not required. Please make sure to have django-hvad installed and well prepared, then make sure, that all django-booking are in your database.

If not re-run all migrations of this app.
