### ISSUE TITLE
Missing base.html

### ISSUE THREAD

**Issue by lawhorkl** [bitmazk/django-booking#4]
So you release a project on GH and don't include the base.html? Nice.

**Comment by mbrochh** [comment]
What the hell are you talking about? This is a reusable app, not a full project.

Apps don't come with base.html files.

**Comment by lawhorkl** [comment]
https://github.com/llazzaro/django-scheduler

and like 8 different apps. If it doesn't come with a base.html, don't require it when you make your templates.

**Comment by mbrochh** [comment]
django-scheduler is a project, not an app and that's why it has a 'site_base.html'
