### ISSUE TITLE
Does this work with Django 1.8.2

### ISSUE THREAD

**Issue by Jzarecta** [bitmazk/django-booking#5]
Wonder if this has succesfully worked with Django 1.8.2 and if there are any issues regarding the code implementation and/or dependencies.

**Comment by mbrochh** [comment]
@Jzarecta I'm afraid we have never tried. My guts feeling is that this should probably work or at least be very little effort to get it working. I think we just need to rename the `migrations` folder into `south_migrations` and then initiate a new `migrations` folder which uses the core migrations module.

Then we need to document that south users need to specify that their old south-based projects should look for the `south_migrations` folder and everyone else who wants to upgrade needs to make sure that
1. they update to this latest version and run the migrations
2. now they disable south and switch to core migrations, there will only be one initial migration and they should run it with the --fake flag

@Tyrdall @dkaufhold do you remember if we ever used this in a 1.8 project?

**Comment by Tyrdall** [comment]
@mbrochh @dkaufhold I haven't.

**Comment by dkaufhold** [comment]
@mbrochh @Tyrdall me neither.
django-libs is ready for 1.8, right? Other than that I'd agree with it only being the migrations that need to be changed.

**Comment by mbrochh** [comment]
Ok sounds good. I think if no one else sends a pull request, I'd like to give the migrations thing a go sometime this week before Sunday.

**Comment by taek** [comment]
@mbrochh Have you tried this in django 1.8? Or, has anyone else tried this in django 1.8 to get it successfully working?

**Comment by Tyrdall** [comment]
Works with 0.7.2
