### ISSUE TITLE
create the view booking.forms.BookingIDAuthenticationForm.

### ISSUE THREAD

**Issue by david-jerry** [bitmazk/django-booking#9]
please how do i create this view? currently i confused what am supposed to do here..

**Comment by dkaufhold** [comment]
Please review Django Docs on how to create a `FormView` https://docs.djangoproject.com/en/1.10/ref/class-based-views/generic-editing/#formview

There you will need the `BookingIDAuthenticationForm`.

The generic `FormView` has a `form_valid` method https://ccbv.co.uk/projects/Django/1.9/django.views.generic.edit/FormView/
In that method, you'll need to call `auth_login(request, form.get_user())`.
Check Django's own login view for reference.
